MotorCycle Booking Backend App
Kaiserabbas/motorcycle_booking_back_end pull request #26
Opened 2024-01-10 11:13 UTC by Kaiserabbas

## MotorCycle Booking Backend App

- Created a new Rails app.
- Defined models.
- Generated migration files.
- Set up associations.
- Generated controllers boilerplates.
- Added doctor names to appointments.
- Set up routes.
- Added authentication.
- Implemented a city column in appointments.
- Updated seeds, models, and controllers.
- Added uniqueness validation to username.
- Configured application and CORS initializers.
- Fixed Swagger documentation issues.
- Updated API docs title.
- Implemented token authorization in Swagger.
- Configured production environment settings.
- Added render configuration and script.
- Corrected RSpec and linters errors.

Recorded this [Zoom]()
Here's https://github.com/Kaiserabbas/motorcycle_booking_front_end/pull/21 to the front-end UI pull request

2024-01-10 19:02 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!








### Main takeaway:  The server on the cloud works.  The server code on GitHub does not.

#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2024-01-10 19:02 UTC, Meltrust commented on app/controllers/api/v1/motorcycles_controller.rb
> +  end
- [ ] What happens here if the Motorcycle is not successfully destroyed?  Kindly, add some error handling like you did on the create method (line 23). 👍

2024-01-10 19:02 UTC, Meltrust commented on README.md
> +  rspec
- [ ]  You are using Rspec, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2024-01-10 19:44 UTC, Graciano1997 commented
Thanks 🙏 very much we will fix it

2024-01-11 03:09 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!










#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2024-01-11 03:09 UTC, Meltrust commented on README.md
> +<p align="center">
- [ ] Kindly, go to the frontend repo to see the [review ](https://github.com/Kaiserabbas/motorcycle_booking_front_end/pull/21#pullrequestreview-1814587538)comment. 👍

2024-01-11 11:43 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight


- Superb job ✔️  



Cheers and Happy coding!👏👏👏


------

2024-01-11 11:49 UTC, merged